---
deployment:
  tasks:
    - export DEPLOYPATH=/home/u1658370/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
    - /bin/cp artikel.html $DEPLOYPATH
    - /bin/cp donasi.html $DEPLOYPATH
    - /bin/cp sylabus.html $DEPLOYPATH
    - /bin/cp other.css $DEPLOYPATH
    - /bin/cp scripts.js $DEPLOYPATH
    - /bin/cp -R image $DEPLOYPATH
    - /bin/cp -R bootstrap $DEPLOYPATH